#!/usr/bin/python3

import subprocess
import argparse

MIN_BRIGHTNESS = 1
DEFAULT_STEP = 5
FIRST_TARGET = DEFAULT_STEP


parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group()

group.add_argument(
    '--up',
    nargs='?',
    const=DEFAULT_STEP,
    type=int
)
group.add_argument(
    '--down',
    nargs='?',
    const=DEFAULT_STEP,
    type=int
)

args = parser.parse_args()


def get_current_brightness() -> int | None:
    try:
        result = subprocess.run(['brightnessctl', 'get', '-P'], capture_output=True, text=True, check=True)
        current_brightness = result.stdout.strip()
        return int(current_brightness)
    except subprocess.CalledProcessError as e:
        print(f'Error getting brightness: {e}')
        return None
    except ValueError:
        print('Could not parse output from brightnessctl')
        return None


def set_current_brightness(percentage: int) -> bool:
    try:
        percentage = max(1, min(100, percentage))
        subprocess.run(['brightnessctl', 'set', f'{percentage}%', '-q'], check=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f'Error setting brightness: {e}')
        return False



if __name__ == '__main__':
    current_brightness = get_current_brightness() 

    if args.up:
        if (current_brightness < FIRST_TARGET) and (args.up == DEFAULT_STEP):
            new_brightness = FIRST_TARGET
        else:
            new_brightness = current_brightness + args.up

    elif args.down:
        new_brightness = current_brightness - args.down


    set_current_brightness(new_brightness)
